### ISSUE TITLE
Change nomenclature from lightsheet to image processing pipeline

### ISSUE THREAD

**Issue by davidackerman** [JaneliaSciComp/lightsheet-pipeline#31]
Currently a lot of names, including the url, uses "lightsheet" rather than some form of image processing pipeline. We should update these with a standard - more generic - name.

**Comment by ntj** [comment]
The URL is changed to 'pipeline' now. Internal names (DB name) still refer to lightsheet, but as long as we know what's meant, that's fine I think.
